//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedToolkit.Assertions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AssertionLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssertionLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TedToolkit.Assertions.Resources.AssertionLocalization", typeof(AssertionLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}all satisfy {Expression}, but the ones at these {Indexes} aren&apos;t..
        /// </summary>
        internal static string AllSatisfyAssertion {
            get {
                return ResourceManager.GetString("AllSatisfyAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}be assignable to {ExpectedType}, but it is {ValueType}..
        /// </summary>
        internal static string AssignableAssertion {
            get {
                return ResourceManager.GetString("AssignableAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}contain {ExpectedValue}, but there are {Subjects}..
        /// </summary>
        internal static string ContainAssertion {
            get {
                return ResourceManager.GetString("ContainAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}have an item matching {Expression}, but there are {Subjects}..
        /// </summary>
        internal static string ContainExpressionAssertion {
            get {
                return ResourceManager.GetString("ContainExpressionAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}have a single item which is {ExpectedValue}, but there are {MatchedCount} item(s)..
        /// </summary>
        internal static string ContainSingleAssertion {
            get {
                return ResourceManager.GetString("ContainSingleAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}have a single item matching {Expression}, but there are {MatchedCount} item(s)..
        /// </summary>
        internal static string ContainSingleExpressionAssertion {
            get {
                return ResourceManager.GetString("ContainSingleExpressionAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COULD.
        /// </summary>
        internal static string Could {
            get {
                return ResourceManager.GetString("Could", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}contain {ExpectedCount} item(s), but there are {ActualCount} item(s)..
        /// </summary>
        internal static string CountAssertion {
            get {
                return ResourceManager.GetString("CountAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}contain more than {ExpectedCount} item(s), but there are {ActualCount} item(s)..
        /// </summary>
        internal static string CountGreaterAssertion {
            get {
                return ResourceManager.GetString("CountGreaterAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}contain at least {ExpectedCount} item(s), but there are {ActualCount} item(s)..
        /// </summary>
        internal static string CountGreaterOrEqualAssertion {
            get {
                return ResourceManager.GetString("CountGreaterOrEqualAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}contain fewer than {ExpectedCount} item(s), but there are {ActualCount} item(s)..
        /// </summary>
        internal static string CountLessAssertion {
            get {
                return ResourceManager.GetString("CountLessAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}contain at most {ExpectedCount} item(s), but there are {ActualCount} item(s)..
        /// </summary>
        internal static string CountLessOrEqualAssertion {
            get {
                return ResourceManager.GetString("CountLessOrEqualAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}be empty, but it is {Subject}..
        /// </summary>
        internal static string EmptyAssertion {
            get {
                return ResourceManager.GetString("EmptyAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}be defined, but it is {Subject}..
        /// </summary>
        internal static string EnumDefinedAssertion {
            get {
                return ResourceManager.GetString("EnumDefinedAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}be {ExpectedValue}, but it is {Subject}..
        /// </summary>
        internal static string EqualityAssertion {
            get {
                return ResourceManager.GetString("EqualityAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}have flag {Flag}, but it is {Subject}..
        /// </summary>
        internal static string FlagAssertion {
            get {
                return ResourceManager.GetString("FlagAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}be greater than {ComparedValue}, but it is {Subject}..
        /// </summary>
        internal static string GreaterAssertion {
            get {
                return ResourceManager.GetString("GreaterAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}be greater than or equal to {ComparedValue}, but it is {Subject}..
        /// </summary>
        internal static string GreaterOrEqualAssertion {
            get {
                return ResourceManager.GetString("GreaterOrEqualAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}have a value, but it is {Subject}..
        /// </summary>
        internal static string HaveValueAssertion {
            get {
                return ResourceManager.GetString("HaveValueAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}be less than {ComparedValue}, but it is {Subject}..
        /// </summary>
        internal static string LessAssertion {
            get {
                return ResourceManager.GetString("LessAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}be less than or equal to {ComparedValue}, but it is {Subject}..
        /// </summary>
        internal static string LessOrEqualAssertion {
            get {
                return ResourceManager.GetString("LessOrEqualAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}match {Expression}, but it is {Subject}..
        /// </summary>
        internal static string MatchAssertion {
            get {
                return ResourceManager.GetString("MatchAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}match {Expression} {ExpectedMatchCount} times, but it is {ActualMatchCount} times..
        /// </summary>
        internal static string MatchCountAssertion {
            get {
                return ResourceManager.GetString("MatchCountAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST.
        /// </summary>
        internal static string Must {
            get {
                return ResourceManager.GetString("Must", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not .
        /// </summary>
        internal static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}be null, but it is {Subject}..
        /// </summary>
        internal static string NullAssertion {
            get {
                return ResourceManager.GetString("NullAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}be one of {ExpectedValues}, but it is {Subject}..
        /// </summary>
        internal static string OneOfAssertion {
            get {
                return ResourceManager.GetString("OneOfAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}be between {MinimumValue} and {MaximumValue}, but it is {Subject}..
        /// </summary>
        internal static string RangeAssertion {
            get {
                return ResourceManager.GetString("RangeAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because: {0}.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOULD.
        /// </summary>
        internal static string Should {
            get {
                return ResourceManager.GetString("Should", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data [{SubjectName}] {AssertionType} {Not}be type of {ExpectedType}, but it is {ValueType}..
        /// </summary>
        internal static string TypeAssertion {
            get {
                return ResourceManager.GetString("TypeAssertion", resourceCulture);
            }
        }
    }
}
