//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedToolkit.PureConst.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TedToolkit.PureConst.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t use Const Attribute on an accessor..
        /// </summary>
        internal static string PC0001Description {
            get {
                return ResourceManager.GetString("PC0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t use Const Attribute on the accessor [{0}]..
        /// </summary>
        internal static string PC0001MessageFormat {
            get {
                return ResourceManager.GetString("PC0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t use Const Attribute on an accessor..
        /// </summary>
        internal static string PC0001Tittle {
            get {
                return ResourceManager.GetString("PC0001Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify this field here, becasue the mtethod is const.
        /// </summary>
        internal static string PC0002Description {
            get {
                return ResourceManager.GetString("PC0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify the field [{0}] here, becasue the mtethod is const.
        /// </summary>
        internal static string PC0002MessageFormat {
            get {
                return ResourceManager.GetString("PC0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify this field here, becasue the mtethod is const.
        /// </summary>
        internal static string PC0002Tittle {
            get {
                return ResourceManager.GetString("PC0002Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify this property here, becasue the method is const.
        /// </summary>
        internal static string PC0003Description {
            get {
                return ResourceManager.GetString("PC0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify the property [{0}] here, becasue the method is const.
        /// </summary>
        internal static string PC0003MessageFormat {
            get {
                return ResourceManager.GetString("PC0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify this property here, becasue the method is const.
        /// </summary>
        internal static string PC0003Tittle {
            get {
                return ResourceManager.GetString("PC0003Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t invoke this method here, becasue the method is const.
        /// </summary>
        internal static string PC0004Description {
            get {
                return ResourceManager.GetString("PC0004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t invoke the method [{0}] here, becasue the method is const.
        /// </summary>
        internal static string PC0004MessageFormat {
            get {
                return ResourceManager.GetString("PC0004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t invoke this method here, becasue the method is const.
        /// </summary>
        internal static string PC0004Tittle {
            get {
                return ResourceManager.GetString("PC0004Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify this variable here, because it is const.
        /// </summary>
        internal static string PC0005Description {
            get {
                return ResourceManager.GetString("PC0005Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify the variable [{0}] here, because it is const.
        /// </summary>
        internal static string PC0005MessageFormat {
            get {
                return ResourceManager.GetString("PC0005MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify this variable here, because it is const.
        /// </summary>
        internal static string PC0005Tittle {
            get {
                return ResourceManager.GetString("PC0005Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify this field here, becasue the method is const.
        /// </summary>
        internal static string PC0006Description {
            get {
                return ResourceManager.GetString("PC0006Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify the field [{0}] here, becasue the method is const.
        /// </summary>
        internal static string PC0006MessageFormat {
            get {
                return ResourceManager.GetString("PC0006MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify this field here, becasue the method is const.
        /// </summary>
        internal static string PC0006Tittle {
            get {
                return ResourceManager.GetString("PC0006Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify this property here, becasue the method is const.
        /// </summary>
        internal static string PC0007Description {
            get {
                return ResourceManager.GetString("PC0007Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify the property {0} here, becasue the method is const.
        /// </summary>
        internal static string PC0007MessageFormat {
            get {
                return ResourceManager.GetString("PC0007MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify this property here, becasue the method is const.
        /// </summary>
        internal static string PC0007Tittle {
            get {
                return ResourceManager.GetString("PC0007Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t invoke this method here, becasue the method is const.
        /// </summary>
        internal static string PC0008Description {
            get {
                return ResourceManager.GetString("PC0008Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t invoke the method[{0}] here, becasue the method is const.
        /// </summary>
        internal static string PC0008MessageFormat {
            get {
                return ResourceManager.GetString("PC0008MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t invoke this method here, becasue the method is const.
        /// </summary>
        internal static string PC0008Tittle {
            get {
                return ResourceManager.GetString("PC0008Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify this variable here, because it is const.
        /// </summary>
        internal static string PC0009Description {
            get {
                return ResourceManager.GetString("PC0009Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify the variable [{0}] here, because it is const.
        /// </summary>
        internal static string PC0009MessageFormat {
            get {
                return ResourceManager.GetString("PC0009MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t modify this variable here, because it is const.
        /// </summary>
        internal static string PC0009Tittle {
            get {
                return ResourceManager.GetString("PC0009Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the checking symbol.
        /// </summary>
        internal static string PC1001Description {
            get {
                return ResourceManager.GetString("PC1001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [{0}] is the checking symbol.
        /// </summary>
        internal static string PC1001MessageFormat {
            get {
                return ResourceManager.GetString("PC1001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the checking symbol.
        /// </summary>
        internal static string PC1001Tittle {
            get {
                return ResourceManager.GetString("PC1001Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find the symbol..
        /// </summary>
        internal static string PC1002Description {
            get {
                return ResourceManager.GetString("PC1002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find the symbol {0}..
        /// </summary>
        internal static string PC1002MessageFormat {
            get {
                return ResourceManager.GetString("PC1002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find the symbol.
        /// </summary>
        internal static string PC1002Tittle {
            get {
                return ResourceManager.GetString("PC1002Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional varaible for checking.
        /// </summary>
        internal static string PC1003Description {
            get {
                return ResourceManager.GetString("PC1003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable {0} was added to check.
        /// </summary>
        internal static string PC1003MessageFormat {
            get {
                return ResourceManager.GetString("PC1003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Varaible.
        /// </summary>
        internal static string PC1003Tittle {
            get {
                return ResourceManager.GetString("PC1003Tittle", resourceCulture);
            }
        }
    }
}
